# install firstly color schemes from here: https://github.com/alacritty/alacritty-theme?tab=readme-ov-file

import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

live_config_reload = true

[selection]
save_to_clipboard = true

[terminal]

osc52 = "CopyPaste"

[cursor]
style="Beam"


[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
#family = "Hack Nerd Font"
#style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"


[[keyboard.bindings]]
key ="C" 
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"



[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Command"

[window]
decorations = "Full"
dynamic_padding = true
opacity = 0.93
blur = true
startup_mode="Maximized"


[window.padding]
x = 15
y = 15
